#!/usr/bin/env python3
"""Make the VM logo (decision D-41 look): the GitHub avatar's idea, a bold VM
glowing on a dark circuit board, in the brand colours and font. Space Mono
Bold outlined to paths, indigo -> violet fill with a soft glow, near-black
board with faint traces. No text, fonts or external references, so it renders
inside GitHub's <img> sandbox.
Needs: python3 -m pip install fonttools brotli
Run:   python3 scripts/make-logo.py   ->  assets/logo/vm-logo-v1-{dark,light}.svg
Avatar PNG: open the dark SVG in a browser at 460x460 and export (see README).
"""
import importlib.util
import os
import random

HERE = os.path.dirname(__file__)
ROOT = os.path.normpath(os.path.join(HERE, ".."))
_spec = importlib.util.spec_from_file_location("mb", os.path.join(HERE, "make-banner.py"))
mb = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(mb)

HEAD = ("<!-- velimir-mueller logo (D-41). VM outlined from Space Mono Bold (SIL OFL 1.1). "
        "Generated by scripts/make-logo.py. Do not edit by hand. -->")

# Brand tokens (site + profile): indigo #6366f1 -> violet #8b5cf6, emerald for the node dots.
THEMES = {
    "dark": dict(bg0="#111114", bg1="#09090b", trace="#6366f1", trace_a=0.16, node="#10b981",
                 a="#818cf8", b="#a78bfa", hi="#eef2ff", glow="#6366f1", glow_a=0.55, rim="#26262b"),
    "light": dict(bg0="#ffffff", bg1="#f4f4f5", trace="#4f46e5", trace_a=0.12, node="#059669",
                  a="#4f46e5", b="#7c3aed", hi="#ffffff", glow="#6366f1", glow_a=0.25, rim="#e4e4e7"),
}


def traces(size, th, seed=20261009):
    """Circuit traces: right-angle runs with a node dot at the end. A run that
    would cross the letters (or the underline) is dropped, so the mark stays clean."""
    rnd = random.Random(seed)
    out = []
    step = size / 16
    keep_out = (size * 0.18, size * 0.24, size * 0.82, size * 0.80)  # x0, y0, x1, y1

    def inside(px, py):
        x0, y0, x1, y1 = keep_out
        return x0 < px < x1 and y0 < py < y1

    def crosses(ax, ay, bx, by):
        return any(inside(ax + (bx - ax) * k / 20, ay + (by - ay) * k / 20) for k in range(21))

    while len(out) < 2 * 18:
        x = rnd.randint(0, 16) * step
        y = rnd.randint(0, 16) * step
        if inside(x, y):
            continue
        pts = [(x, y)]
        for _ in range(rnd.randint(1, 3)):
            if rnd.random() < 0.5:
                x += rnd.choice([-1, 1]) * rnd.randint(1, 4) * step
            else:
                y += rnd.choice([-1, 1]) * rnd.randint(1, 4) * step
            pts.append((x, y))
        if any(crosses(*a, *b) for a, b in zip(pts, pts[1:])):
            continue
        d = " ".join(f"{'M' if i == 0 else 'L'}{px:.1f} {py:.1f}" for i, (px, py) in enumerate(pts))
        out.append(f'<path d="{d}" fill="none" stroke="{th["trace"]}" stroke-opacity="{th["trace_a"]}" '
                   f'stroke-width="{size/170:.1f}" stroke-linecap="round" stroke-linejoin="round"/>')
        out.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{size/120:.1f}" fill="{th["node"]}" fill-opacity="0.55"/>')
    return out


def mark(theme, size=512, uid=None):
    """The logo's elements without the <svg> wrapper, for embedding (ids prefixed by uid)."""
    return "\n".join(_elements(theme, size, uid or f"vm-logo-{theme}"))


def logo(theme, size=512):
    return "\n".join([
        HEAD,
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="{size}" height="{size}" '
        f'role="img" aria-label="VM, Velimir Müller"><title>Velimir Müller</title>',
        *_elements(theme, size, f"vm-logo-{theme}"),
        "</svg>",
    ]) + "\n"


def _elements(theme, size, uid):
    th = THEMES[theme]
    fsize = size * 0.42
    w = mb.MONO_B.width("VM", fsize, track=fsize * 0.03)
    x = (size - w) / 2
    y = size / 2 + fsize * mb.MONO_B.cap / 2
    d, _ = mb.MONO_B.path("VM", fsize, x, y, track=fsize * 0.03)
    return [
        "<defs>",
        f'<radialGradient id="{uid}-bg" cx="0.5" cy="0.42" r="0.75"><stop offset="0" stop-color="{th["bg0"]}"/>'
        f'<stop offset="1" stop-color="{th["bg1"]}"/></radialGradient>',
        f'<linearGradient id="{uid}-fill" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{th["a"]}"/>'
        f'<stop offset="1" stop-color="{th["b"]}"/></linearGradient>',
        f'<linearGradient id="{uid}-hi" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="{th["hi"]}" stop-opacity="0.55"/>'
        f'<stop offset="0.5" stop-color="{th["hi"]}" stop-opacity="0"/></linearGradient>',
        f'<filter id="{uid}-glow" x="-30%" y="-30%" width="160%" height="160%">'
        f'<feGaussianBlur stdDeviation="{size/40:.1f}"/></filter>',
        f'<clipPath id="{uid}-clip"><rect width="{size}" height="{size}" rx="{size*0.22:.1f}"/></clipPath>',
        "</defs>",
        f'<g clip-path="url(#{uid}-clip)">',
        f'<rect width="{size}" height="{size}" fill="url(#{uid}-bg)"/>',
        *traces(size, th),
        # glow behind the letters, then the letters, then a top highlight like the silver original
        f'<path d="{d}" fill="{th["glow"]}" fill-opacity="{th["glow_a"]}" filter="url(#{uid}-glow)"/>',
        f'<path d="{d}" fill="url(#{uid}-fill)"/>',
        f'<path d="{d}" fill="url(#{uid}-hi)"/>',
        f'<rect x="{size*0.39:.1f}" y="{y + fsize*0.16:.1f}" width="{size*0.22:.1f}" height="{size/110:.1f}" rx="2" fill="url(#{uid}-fill)"/>',
        "</g>",
        f'<rect x="0.5" y="0.5" width="{size-1}" height="{size-1}" rx="{size*0.22:.1f}" fill="none" stroke="{th["rim"]}"/>',
    ]


def main():
    for theme in THEMES:
        path = os.path.join(ROOT, "assets", "logo", f"vm-logo-v1-{theme}.svg")
        with open(path, "w", encoding="utf-8") as f:
            f.write(logo(theme))
        print(path)


if __name__ == "__main__":
    main()
