#!/usr/bin/env python3
"""Make the profile hero banner and the flagship cards (dark + light).

Look: velimir-mueller.de + code-context dashboard (decision D-41, see the
synthwerk repo docs/presence-style.md). Reuses the outline helpers from
make-banner.py: all text is outlined to paths, so the SVGs render inside
GitHub's <img> sandbox. Art panels embed assets/art/<name>.jpg as a data URI
when the file exists, else a vector fallback is drawn.

Needs: python3 -m pip install fonttools brotli
Run:   python3 scripts/make-profile.py [--version v1]
"""
import argparse
import base64
import importlib.util
import os
from xml.sax.saxutils import escape, quoteattr

HERE = os.path.dirname(__file__)
ROOT = os.path.normpath(os.path.join(HERE, ".."))
_spec = importlib.util.spec_from_file_location("mb", os.path.join(HERE, "make-banner.py"))
mb = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(mb)
_lspec = importlib.util.spec_from_file_location("ml", os.path.join(HERE, "make-logo.py"))
ml = importlib.util.module_from_spec(_lspec)
_lspec.loader.exec_module(ml)
THEMES, MONO, MONO_B, SANS, t, pill, defs, page, card = (
    mb.THEMES, mb.MONO, mb.MONO_B, mb.SANS, mb.t, mb.pill, mb.defs, mb.page, mb.card)

HEAD = ("<!-- velimir-mueller profile (D-41). Text outlined from Space Mono and Inter "
        "(SIL OFL 1.1). No live text, no fonts, no external references. "
        "Generated by scripts/make-profile.py. Do not edit by hand. -->")

FLAGSHIPS = [
    dict(
        key="synthwerk", index="01", status="IN DEVELOPMENT · M0", word="SYNTHWERK.",
        label="MODULAR AI SERVICES", sublabel="GO · PYTHON · NUXT · TYPESCRIPT · SELF-HOSTED",
        tagline=["Small services for AI chat, image labels and page building.",
                 "One blueprint for CI, lint, docs and reviews across every repo."],
        stats=[("8", "REPOS"), ("93.1%", "VISION EVAL"), ("MIT", "LICENSE")],
    ),
    dict(
        key="code-context", index="02", status="RELEASED · NPM v2.8", word="CODE CONTEXT.",
        label="MCP SERVER FOR AI CODING AGENTS", sublabel="TYPESCRIPT · SQLITE · DASHBOARD",
        tagline=["Indexes a codebase into structured context for agents,",
                 "with persistent sprint and retro memory."],
        stats=[("81", "TOOLS"), ("~40%", "FEWER TOKENS"), ("9", "BENCHMARK TASKS")],
    ),
    dict(
        key="portfolio", index="03", status="LIVE · v2.3", word="PORTFOLIO.",
        label="VELIMIR-MUELLER.DE", sublabel="NEXT.JS · SUPABASE · VERCEL · WASM",
        tagline=["Bilingual site with live demos, a Rust/WASM arcade",
                 "and first-party, cookieless analytics."],
        stats=[("0", "COOKIES"), ("3", "LIVE DEMOS"), ("2", "LOCALES")],
    ),
]


def svg_doc(W, H, label, parts):
    return (f'{HEAD}\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" '
            f'height="{H}" role="img" aria-label={quoteattr(label)}><title>{escape(label)}</title>\n'
            + "\n".join(parts) + "\n</svg>\n")


def label_block(ix, y, label, sublabel, th, size=17):
    """Indigo accent line + Space Mono label + faint sub label. y = label baseline."""
    out = [f'<rect x="{ix}" y="{y - 6:.1f}" width="44" height="2" fill="{th["indigo"]}"/>']
    a, _ = t(MONO, label, size, ix + 62, y, th["sub"], track=size * 0.19)
    b, _ = t(MONO, sublabel, 11, ix + 62, y + 22, th["faint"], track=2.2)
    return out + [a, b]


def tagline_block(ix, y, lines, th, size=17):
    out = [f'<rect x="{ix}" y="{y - 18:.1f}" width="2" height="{23 * len(lines) + 3}" fill="{th["card_line"]}"/>']
    for i, line in enumerate(lines):
        p, _ = t(SANS, line, size, ix + 18, y + 23 * i, th["sub"])
        out.append(p)
    return out


def hero(theme):
    th = THEMES[theme]
    W, H, pad, gap, rw = 1280, 540, 32, 20, 400
    uid = f"vm-hero-{theme}"
    lx, ly, lh = pad, pad, H - 2 * pad
    lw = W - 2 * pad - gap - rw
    rx = lx + lw + gap
    parts = [defs(uid, th, W, H), page(uid, th, W, H), card(lx, ly, lw, lh, th),
             card(rx, ly, rw, lh, th, uid, grid=True)]

    ix, top = lx + 36, ly + 30
    # Brand lockup: the VM logo mark, then the pill beside it.
    ms = 44
    parts.append(f'<g transform="translate({ix},{top - 9}) scale({ms / 512})">{ml.mark(theme, 512, uid=f"{uid}-mark")}</g>')
    p, _ = pill(ix + ms + 14, top, "BERLIN · BUILDING WITH AI, NOT BY AI", th)
    parts.append(p)
    size, y = 96, top + 58 + 96 * 0.70
    for line in ("VELIMIR", "MÜLLER."):
        w, _ = t(MONO_B, line, size, ix - size * 0.04, y, th["text"], track=-size * 0.04)
        parts.append(w)
        y += size * 1.0
    y -= size * 0.14
    parts += label_block(ix, y, "SENIOR PRODUCT ENGINEER", "FULL-STACK · INFRASTRUCTURE · AGENT TOOLING", th)
    parts += tagline_block(ix, y + 62, ["I ship products end to end, and I build the AI tooling",
                                         "that makes me faster while I stay in charge."], th)

    # right card: the stance
    mx = rx + rw / 2
    ry = ly + 100
    p, _ = pill(mx, ry, "HUMAN IN THE LOOP", th, size=10.5, center=True)
    parts.append(p)
    yy = ry + 80
    for line in ("Models propose.", "Rules gate.", "I decide."):
        s, _ = t(MONO_B, line, 28, mx, yy, th["text"], track=-0.6, anchor="middle")
        parts.append(s)
        yy += 38
    yy += 10
    sw = rw - 64
    parts.append(f'<rect x="{rx + 32}" y="{yy:.1f}" width="{sw}" height="46" rx="10" fill="{th["snip_bg"]}"/>')
    d, dw = t(MONO, "$", 12.5, rx + 48, yy + 27.5, th["snip_dim"])
    s, _ = t(MONO, "npx vlm-code-context-mcp", 12.5, rx + 48 + dw + 9, yy + 27.5, th["snip_text"])
    parts += [d, s]
    yy += 46 + 34
    f, fw = t(MONO_B, "velimir-mueller.de", 12, mx, yy, th["text"], track=0.6, anchor="middle")
    parts += [f, f'<rect x="{mx - fw / 2:.1f}" y="{yy + 6:.1f}" width="{fw:.1f}" height="1.2" fill="{th["text"]}"/>']
    return svg_doc(W, H, "Velimir Müller. Senior Product Engineer. Models propose, rules gate, I decide.", parts)


def art_panel(uid, key, x, y, w, h, th):
    """Art image clipped to a 24 px card, or a vector fallback in the glow colours."""
    out = [f'<clipPath id="{uid}-art"><rect x="{x}" y="{y}" width="{w}" height="{h}" rx="24"/></clipPath>',
           f'<g clip-path="url(#{uid}-art)">', f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="#08080a"/>']
    jpg = os.path.join(ROOT, "assets", "art", f"{key}.jpg")
    if os.path.exists(jpg):
        with open(jpg, "rb") as fh:
            data = base64.b64encode(fh.read()).decode()
        out.append(f'<image x="{x}" y="{y}" width="{w}" height="{h}" preserveAspectRatio="xMidYMid slice" '
                   f'href="data:image/jpeg;base64,{data}"/>')
    else:
        cx, cy = x + w / 2, y + h / 2
        for i, (c, a) in enumerate(th["glow"]):
            out.append(f'<circle cx="{cx:.0f}" cy="{cy:.0f}" r="{40 + i * 38}" fill="none" stroke="{c}" '
                       f'stroke-opacity="{a * 2.4:.2f}" stroke-width="1.2"/>')
        out.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="url(#{uid}-grid)"/>')
    out.append("</g>")
    out.append(f'<rect x="{x + 0.5}" y="{y + 0.5}" width="{w - 1}" height="{h - 1}" rx="23.5" fill="none" '
               f'stroke="{th["card_line"]}"/>')
    return out


def flagship(theme, fs):
    th = THEMES[theme]
    W, H, pad, gap, aw = 1280, 380, 24, 20, 440
    uid = f"vm-{fs['key']}-{theme}"
    parts = [defs(uid, th, W, H), page(uid, th, W, H)]
    parts += art_panel(uid, fs["key"], pad, pad, aw, H - 2 * pad, th)
    cx = pad + aw + gap
    cw = W - cx - pad
    parts.append(card(cx, pad, cw, H - 2 * pad, th))

    ix, top = cx + 36, pad + 30
    p, pw = pill(ix, top, fs["status"], th)
    parts.append(p)
    e, _ = t(MONO, f"{fs['index']} / FLAGSHIP", 11, cx + cw - 36, top + 17, th["faint"], track=2.2, anchor="end")
    parts.append(e)
    size = 60
    y = top + 52 + size * 0.70
    w, _ = t(MONO_B, fs["word"], size, ix - size * 0.04, y, th["text"], track=-size * 0.04)
    parts.append(w)
    y += 36
    parts += label_block(ix, y, fs["label"], fs["sublabel"], th, size=15)
    parts += tagline_block(ix, y + 58, fs["tagline"], th, size=16)

    # stats row, like the impact numbers on the website
    sy = H - pad - 30
    sx = ix
    for value, name in fs["stats"]:
        v, vw = t(MONO_B, value, 26, sx, sy, th["text"], track=-0.5)
        n, nw = t(MONO, name, 10, sx + vw + 10, sy, th["faint"], track=1.8)
        parts += [v, n]
        sx += vw + nw + 44
    return svg_doc(W, H, f"{fs['word']} {fs['label'].lower()}. {fs['status'].lower()}.", parts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="v1", help="file name suffix. Use a new one for each change.")
    opt = ap.parse_args()
    for theme in ("dark", "light"):
        jobs = [(os.path.join("banner", f"hero-{opt.version}-{theme}.svg"), hero(theme))]
        jobs += [(os.path.join("cards", f"{fs['key']}-{opt.version}-{theme}.svg"), flagship(theme, fs))
                 for fs in FLAGSHIPS]
        for rel, svg in jobs:
            fn = os.path.join(ROOT, "assets", rel)
            os.makedirs(os.path.dirname(fn), exist_ok=True)
            with open(fn, "w") as fh:
                fh.write(svg)
            print("wrote", fn, os.path.getsize(fn), "bytes")


if __name__ == "__main__":
    main()
